version: '2.1'
services:
  mock-server:
    image: mock-server:dev
    build: .
    volumes:
      - .:/app
    environment:
      - SAMPLE_PATH
    networks:
      static-network:
        ipv4_address: 169.254.169.254
networks:
  static-network:
    ipam:
      config:
        - subnet: 169.254.169.240/28
          gateway: 169.254.169.241
